### ISSUE TITLE
configure modifier failed.

### ISSUE THREAD

**Issue by qianguozheng** [google/martian#136]
I am newbie to golang, and found https://github.com/netroby/gohttpproxy.git this httpproxy using martian, so I run it and with description in martian readme.md page, try to set the modifier, but it is not work out, main reason is as below, there is no `martian.proxy` in host,should I add it in hostname ?or what should I do the make the set of modifiers work.

martian logs as below.

```
--------------------------------------------------------------------------------
Request to http://martian.proxy/configure
--------------------------------------------------------------------------------
POST http://martian.proxy/configure HTTP/1.1
Host: martian.proxy
Content-Length: 98
Accept: */*
Content-Type: application/json
User-Agent: curl/7.49.1
Via: 1.1 martian
X-Forwarded-For: ::1
X-Forwarded-Host: martian.proxy
X-Forwarded-Proto: http

{  "header.Modifier": {    "scope": ["response"],    "name": "Test-Header",    "value": "true"  }}
--------------------------------------------------------------------------------

2016/10/21 09:03:57 ERROR: martian: failed to round trip: dial tcp: lookup martian.proxy: no such host
2016/10/21 09:03:57 INFO: 
--------------------------------------------------------------------------------
Response from http://martian.proxy/configure
--------------------------------------------------------------------------------
HTTP/1.1 502 Bad Gateway
Content-Length: 0
Warning: 199 "martian" "dial tcp: lookup martian.proxy: no such host" "Fri, 21 Oct 2016 09:03:57 GMT"
```

**Comment by bramhaghosh** [comment]
This is an issue with the main.go in https://github.com/netroby/gohttpproxy.  It's not registering "martian.proxy/{path}" as a pattern in the http.DefaultServeMux.  For an example of how to do that, refer to https://github.com/google/martian/blob/master/cmd/proxy/main.go#L402

Alternatively, just use https://github.com/google/martian/blob/master/cmd/proxy/main.go.

**Comment by bramhaghosh** [comment]
The implementation in that main.go does not register martian.proxy a part
of the pattern in the servemux for config requests.  Take a look at
https://github.com/google/martian/blob/master/cmd/proxy/main.go for an
example that does. Specifically the config function.

**Comment by qianguozheng** [comment]
Thanks @bramhaghosh
