### ISSUE TITLE
How to add filter for modifer response in martian ?

### ISSUE THREAD

**Issue by qianguozheng** [google/martian#174]
I saw the sample of add key-value pair in example, but not find how to modify the content of response in the README.

could any body show me how to do that?
For example, when the http response body have the data "hello", replace it with a word "world".

BTW, will martian decompress the http response data that compressed?

**Comment by qianguozheng** [comment]
@bramhaghosh

**Comment by bramhaghosh** [comment]
This would be implemented with a custom response modifier - you'd be best off taking a look at body_modifier.go to see how to read out the response body and replace it.
