### ISSUE TITLE
RFC 7231 4.3.6:     A server MUST NOT send any Transfer-Encoding or Content-Length header    fields in a 2xx (Successful) response to CONNECT

### ISSUE THREAD

**Issue by netroby** [google/martian#209]
RFC 7231 4.3.6:

   A server MUST NOT send any Transfer-Encoding or Content-Length header
   fields in a 2xx (Successful) response to CONNECT.  A client MUST
   ignore any Content-Length or Transfer-Encoding header fields received
   in a successful response to CONNECT.

Full bug report see https://github.com/curl/curl/issues/1317

The current martian proxy handle CONNECT, will response 
* About to connect() to proxy 192.168.17.1 port 8123 (#0)
*   Trying 192.168.17.1...
* Connected to 192.168.17.1 (192.168.17.1) port 8123 (#0)
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.29.0
> Proxy-Connection: Keep-Alive
> 

< HTTP/1.1 200 OK
< Content-Length: 0
< 

The Content-Length must not response

**Comment by netroby** [comment]
ping @bramhaghosh

**Comment by bramhaghosh** [comment]
Fixed with #210
