### ISSUE TITLE
https proxy

### ISSUE THREAD

**Issue by lengrongfu** [google/martian#236]
我需要代理访问https请求的网站，并且修改请求头，请求如何做？

**Comment by hueich** [comment]
To proxy https requests, you need to create or use an existing certificate to start the proxy.  The client/browser that's connecting through the proxy will need to trust the cert.  To modify the request header, you can use the header modifier.  Both of these functionality should be available in the default proxy main.go.  You just have to pass the path of the cert through command line, and start the proxy.  After the proxy is up, you can configure the proxy to add a header modifier by sending a POST request to http://<proxyhost>/configure with the JSON config.
