### ISSUE TITLE
New Modifier Type: Notifier

### ISSUE THREAD

**Issue by bramhaghosh** [google/martian#240]
A notifier is a modifier that executes a WebHook (HTTP callback) when the modifier is evaluated in the modifier tree. 

A notifier would take a target URL and a message string. When MoidfyRequest or ModifyResponse is executed, a POST request is sent to the the target URL with the message string as the request body.

Might take separate target URLs and messages for request or response to provide control over whether to execute the callback on request or response.

**Comment by admtnnr** [comment]
What would the webhook payload look like?
