### ISSUE TITLE
Allow rendering HAR logs as JSONP via query param

### ISSUE THREAD

**Issue by caccialdo** [google/martian#257]
The popular online HAR viewer tool at http://www.softwareishard.com/har/viewer has the ability of loading (via an ajax request so even local URLs work) any HAR from its URL if this HAR is formatted as 

```js
onInputData(harJson);
```

If Martian allowed for this format change via, let's say, a query param (`?jsonp=1`) we could go to http://www.softwareishard.com/har/viewer?inputUrl=http://martian.proxy/logs?jsonp=1 to get instant rendering of the HAR timeline.

**Comment by caccialdo** [comment]
To be 100% fair, the author of the viewer could also make the URL input method work with regular JSON responses...

**Comment by caccialdo** [comment]
More investigation shows that the [master version of the viewer project](https://github.com/janodvarko/harviewer) does indeed support plain HAR inputs via the `har` query param. However CORS headers are required to make this works, which the martian API doesn't pass in its responses at the moment.

If that was the case, simply navigating to http://gitgrimbo.github.io/harviewer/master/?har=http://martian.proxy/logs would have the intended effect.

**Comment by hnovikov** [comment]
Have you tried starting martian with --cors?

**Comment by caccialdo** [comment]
Obviously I didn't...

![facepalm](https://user-images.githubusercontent.com/1080761/42956984-40e75606-8b79-11e8-8a3b-ff75d361ab0a.gif)

But I can confirm that running martian with `-cors` does indeed works 👍 
Thanks for the hint @hnovikov !
