### ISSUE TITLE
400 - Bad request and 404- Not founc while extracting HAR logs 

### ISSUE THREAD

**Issue by SagarBShinde** [google/martian#263]
Hi team,
I am trying to use martian proxy on windows 10 host to intercept traffic from my Android mobile.

I started the proxy using the command proxy -v=2  - har=true. 

Proxy is started with default settings [traffic on 8080 and api on 8181]
I am getting following errorss when I try to get the har logs 

GET http://localhost:8181/logs- 400 Bad Request

GET http://localhost:8080/logs- 404 Not Found

I am using Advanced Rest Client to call Martian rest APIs.

Could you please help?

**Comment by SagarBShinde** [comment]
As suggested by Bramha on the google group I was able to fetch logs after passing "--api=localhost" parameter while starting the proxy
I think this should be updated in the read me file

**Comment by 89z** [comment]
https://github.com/google/martian/issues/326
