### ISSUE TITLE
Create a new header from a dynamic value

### ISSUE THREAD

**Issue by thinkingmik** [google/martian#297]
Hi, it is possible to set an header value from another header parameter instead of a static value?

For example:
```json
{
  "header.Modifier": {
    "scope": ["request"],
    "name": "X-Martian",
    "value": "<copy value from header['Y-Martian']>"
  }
}
```

**Comment by admtnnr** [comment]
You can copy a header value to a different header with `header.Copy`, but we don't support altering the header at the same time.

https://github.com/google/martian/blob/master/header/copy_modifier.go#L76

**Comment by thinkingmik** [comment]
Thank you @admtnnr, it works!

```json
"header.Copy": {
   "scope": ["request"],
   "from": "X-Martian",
   "to": "Y-Martian"
}
```
