### ISSUE TITLE
Go 1.13+: one shall not call flag.Parse() in init 

### ISSUE THREAD

**Issue by eclipseo** [google/martian#309]
See bug golang/go#33475 and bug golang/go#31859 for the rationale

> To be clear, we are talking only about flag.Parse here, not flag.*. The flag package is designed so that multiple packages can define flags, without those packages being aware of each other. It's essential that flag.Parse be called only after all flags are defined, meaning only after all packages are initialized. The normal practice is that the main package calls flag.Parse, because the main package is the only package that is sure to run after all packages are initialized.
> 
> Your program may well be designed so that it is OK to call flag.Parse in an init function of some non-main package. But most programs do not and cannot work that way. So I am questioning how much we should twist the testing package to support that use case. Of course if the change to the testing package is simple, then that is fine. But I would not like to see a lot of complexity added to support a very unusual use case.

**Comment by eclipseo** [comment]
See https://github.com/golang/go/issues/31859#issuecomment-489889428 hor a workaround.

**Comment by phaus** [comment]
I just pushed a small update, that helps using this module with go > 1.13.

**Comment by phaus** [comment]
hmmm… I guess this can be close now? 🤔
