### ISSUE TITLE
Retagging of v3.0.0

### ISSUE THREAD

**Issue by medains** [google/martian#313]
Because I use gocenter.io - I noticed that v3@v3.0.0 got retagged sometime recently (and the gocenter.io version now has a sumdb mismatch as a result).

Can a new tag be pushed for v3 to resolve the issue for anyone who might be using gocenter, or who happened to build and now effectively has a poisoned go.sum?

**Comment by friendly-pineapple** [comment]
Ditto, am seeing the same thing.

**Comment by williamsandrew** [comment]
Can also confirm that we're seeing this issue

**Comment by manfredlift** [comment]
Same here

**Comment by bramhaghosh** [comment]
Retagged to 3.1.0 - please confirm that this fixed your issue

**Comment by utkarshmani1997** [comment]
@bramhaghosh This fixed the issue for me

**Comment by medains** [comment]
I'm happy with that - any project still affected can update their module config.
