### ISSUE TITLE
Feature request: Add "positive" at least once verifier

### ISSUE THREAD

**Issue by ehedrick** [google/martian#61]
###### Background:
It would be great to verify that a request has gone through the proxy. This can be very handy when testing to verify that a specific callback has been called for example. In this case there would be an error if the verifier has still not matched any request/response when `GET http://martian.proxy/verify` is called.

###### Example interface:
Verifier:
```
{
  "atLeastOnce.Verifier": {
    "scope": ["request"],
    "host": "example.com",
    "path": "/testing"
  }
}
```

Error:
```
{
  "errors" : [
    {
      "message": "request(http://example.com/testing) call verify failure"
    }
  ]
}
```

**Comment by adamtanner** [comment]
I think [pingback.Verifier](https://github.com/google/martian/blob/master/pingback/pingback_verifier.go) will do what you want. Will that work for what you need or is it missing some functionality?

**Comment by ehedrick** [comment]
You are exactly right. pingback has this exact behavior. Looks like I was just confused by the terminology. Thanks!
