### ISSUE TITLE
Error when installing the package using "go get"

### ISSUE THREAD

**Issue by kkshetty** [google/martian#74]
I tried installing the martian package using the following command

go get github.com/google/martian

This was the error I received.

$GOPATH......./src/github.com/google/martian/proxy.go:142: tr.TLSNextProto undefined (type *http.Transport has no field or method TLSNextProto)

**Comment by bramhaghosh** [comment]
I suspect this is due to Martian moving to Go 1.6. Update your version of
Go to the 1.6 release candidate (1.6rc2), and see if the issue persists.
https://golang.org/dl/

**Comment by kkshetty** [comment]
Upgraded from 1.5.3 to 1.6rc2. Fixed the problem.

Thanks!
